points:
  key: 
    padding: U
    footprints:
      choc_hotswap:
        type: choc
        nets:
          from: =column_net
          to: GND
        params:
            keycaps: true
            reverse: true
            hotswap: true
      choc:
        type: choc
        anchor:
          rotate: 180
        nets:
          from: =column_net
          to: GND
        params:
            keycaps: true
            reverse: true
  zones:
    board:
      anchor:
        rotate: 0
      columns:
        ppinky:
          spread: U
          row_overrides: 
            home:
              bind: [1, 0, 1, 1]
        pinky:
          spread: U
          stagger: -19
          row_overrides:
            lower:
              bind: [0, 1, 1, 1]
            home:
              bind: [0, 3, 0, 1] 
            upper: 
              bind: [1, 3, 3, 1] 
        ring:
          spread: U
          rotate: 
          origin: [-12, -19]
          stagger: 19
          row_overrides:
            lower:
              bind: [0, 1, 1, 1]
            home:
              bind: [0, 3, 3, 1]
            upper: 
              bind: [1, 3, 3, 1]
        middle:
          spread: U
          stagger: 6
          row_overrides:
            lower:
              bind: [0, 1, 1, 1]
            home:
              bind: [0, 3, 3, 1]
            upper: 
              bind: [1, 1, 3, 1] 
        index:
          spread: U  
          stagger: -6
          row_overrides:
            lower:
              bind: [0, 1, 1, 1]
            home:
              bind: [0, 3, 3, 1]
            upper: 
              bind: [1, 3, 3, 1]
        indextra:
          spread: U  
          stagger: 0
          row_overrides:
            lower:
              bind: [0, 1, 1, 1]
            home:
              bind: [0, 1, 3, 1]
            upper: 
              bind: [1, 1, 3, 1] 
      rows:
        lower:
        home:
        top:

    thumb:
      anchor:
        ref: board_indextra_lower
        shift: [0,-19]
      columns:
        home:
          stagger:
          row_overrides:
            upper: 
              bind: [1, 20, 1, 1] 
        indexxtra:
          spread: U  
          stagger: -19
          row_overrides:
            upper:
              bind: [60, 1, 1, 1]
outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1U , 1U]
    cutout:
      - type: outline
        name: raw
        fillet: 2.5
pcbs:
  main:
    outlines:
      main:
        outline: cutout