points:
  key: 
    padding: cx
    footprints:
      choc_hotswap:
        type: choc
        nets:
          from: =column_net
          to: GND
        params:
            keycaps: true
            reverse: true
            hotswap: true
      choc:
        type: choc
        anchor:
          rotate: 180
        nets:
          from: =column_net
          to: GND
        params:
            keycaps: true
            reverse: true
  zones:
    board:
      anchor:
        rotate: 0
      columns:
        ppinky:
          spread: U
          row_overrides: 
            home:
              bind: [1, 0, 1, 1.5]
              column_net: P01
        pinky:
          spread: U
          stagger: -18
          row_overrides:
            lower:
              bind: [0, 1.5, 1, 1.5]
              column_net: P03
            home:
              bind: [0, 3, 0, 1] 
              column_net: P02
            upper: 
              bind: [1, 3, 3, 1.5] 
              column_net: P00
        ring:
          spread: U
          rotate: 
          origin: [-12, -19]
          stagger: 18
          row_overrides:
            lower:
              bind: [0, 1.5, 1, 1]
              column_net: P06
            home:
              bind: [0, 3, 3, 1]
              column_net: P05
            upper: 
              bind: [1, 3, 3, 1.5]
              column_net: P04
        middle:
          spread: U
          stagger: 6
          row_overrides:
            lower:
              bind: [0, 1, 1, 1]
              column_net: P09
            home:
              bind: [0, 3, 3, 1]
              column_net: P08
            upper: 
              bind: [1, 1.5, 3, 1.5] 
              column_net: P07
        index:
          spread: U  
          stagger: -6
          row_overrides:
            lower:
              bind: [0, 1, 1, 1.5]
              column_net: P15
            home:
              bind: [0, 3, 3, 1]
              column_net: P19
            upper: 
              bind: [1, 3, 3, 1]
              column_net: P21
        indextra:
          spread: U  
          stagger: 0
          row_overrides:
            lower:
              bind: [0, 1, 1, 1]
              column_net: P14
            home:
              bind: [0, 1, 3, 1]
              column_net: P18
            upper: 
              bind: [1, 1.5, 3, 1] 
              column_net: P20
      rows:
        lower:
        home:
        top:

    thumb:
      anchor:
        ref: board_indextra_lower
        shift: [0,-18]
      columns:
        home:
          stagger:
          row_overrides:
            upper: 
              bind: [1, 20, 1, 1.5] 
              column_net: P16
        indexxtra:
          spread: U  
          stagger: -18
          row_overrides:
            upper:
              bind: [55, 1.5, 1, 1.5]
              column_net: P10
outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1U , 1U]
    cutout:
      - type: outline
        name: raw
        fillet: 2.5
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false  
pcbs:
  main:
    outlines:
      main:
        outline: cutout